version: "3"
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    ports:
      - "5672:5672"
      - "15672:15672"

  dtupay:
    image: dtupay_backend
    container_name: dtupay_container
    ports:
      - "8080:8080"

  tokenservice:
    image: token-service
    container_name: token_container


  customerservice:
    image: customer
    container_name: customer_container


  merchantservice:
    image: merchant
    container_name: merchant_container


