version: "3"
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container

  dtupay:
    image: dtupay_backend
    container_name: dtupay_container


  tokenservice:
    image: token-service
    container_name: token_container


  customerservice:
    image: customer
    container_name: customer_container


