version: "3"
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    hostname: rabbitMq
    networks:
      - resolute


  dtupay:
    image: dtupay_backend
    container_name: dtupay_container
    networks:
      - resolute


  tokenservice:
    image: token-service
    container_name: token_container
    networks:
      - resolute


  customerservice:
    image: customer
    container_name: customer_container
    networks:
      - resolute


networks:
  resolute:
    external:
        name: resolute