version: "3"
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container

  dtupay:
    image: dtupay_backend
    container_name: dtupay_container
    ports:
      - "8080:8080"

  tokenservice:
    image: token-service
    container_name: token_container
