version: "3"
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  dtupay:
    image: dtupay_backend
    container_name: dtupay_container


  tokenservice:
    image: token-service
    container_name: token_container


  customerservice:
    image: customer
    container_name: customer_container


networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1